In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy as sc
import geopandas as gpd
import contextily as cx
import folium

In [2]:
from osgeo import gdal
import geopandas as gpd
gdal.SetConfigOption('SHAPE_RESTORE_SHX', 'YES')


In [3]:
def dista_eclidiana(c,p):
    'Regresa la distancia euclidiana entre ambos puntos'
    dist=(((c[0]-p[0])**2)+ (c[1]-p[1])**2 )**1/2
    return dist

In [4]:
path=('Data/centros-de-salud/Centros de Salud/Centros_de_salud.shp')

In [5]:
path2=('Data\centromedico_hospitalizacion_2020.shp')

In [6]:
path3='Data\hospitales_y_centros_de_salud.shp'

In [12]:
df_sk1 = gpd.read_file(path)

In [13]:
df_sk2 = gpd.read_file(path2)

In [14]:
df_sk3 = gpd.read_file(path3)

In [15]:
#df_sk3

In [16]:
geo_df_list=df_sk1[df_sk1['ESTATU_OPE']!='FUERA DE OPERACIÓN (TOTAL O PARCIAL)']


In [17]:
geo_df_list.columns

Index(['ID', 'NOM_ENT', 'C__ENTIDAD', 'N_MUNICI', 'C_MUNI', 'N_LOC', 'C_LOC',
       'N_INSTITU', 'TOT_CONSU', 'NOM_UNIDAD', 'ESTATU_OPE', 'LONGITUD',
       'LATITUD', 'tipo_centr', 'geometry'],
      dtype='object')

In [18]:
geo_df_list=geo_df_list[['ID','NOM_UNIDAD','tipo_centr','geometry','LONGITUD','LATITUD']]

In [19]:
#df_sk1['tipo_centr'].value_counts()

In [20]:
geo_df_list

ID                            NOM_UNIDAD tipo_centr  \
0      1                 C.S.T-I HONORATO LEAL        T-I   
1      2              C.S.T-II ERMITA ZARAGOZA       T-II   
2      3   C.S.T-II JOSÉ MARÍA MORELOS Y PAVÓN       T-II   
6      7                      C.S.T-I PROHOGAR        T-I   
7      8            C.S.T-I SAN MIGUEL AMANTLA        T-I   
..   ...                                   ...        ...   
205  206           C.S.T-II CUCHILLA PANTITLÁN       T-II   
206  207   C.S.T-III DR. JUAN DUQUE DE ESTRADA      T-III   
207  208            C.S.T-III DR. LUIS E. RUÍZ      T-III   
208  209  C.S.T-III BEATRIZ VELASCO DE ALEMÁN.      T-III   
209  210                       C.S.T-III OASIS      T-III   

                       geometry            LONGITUD             LATITUD  
0    POINT (-99.05190 19.35110)            -99.0519             19.3511  
1    POINT (-99.01586 19.41464)          -98.595985           19.214778  
2    POINT (-99.12100 19.44540)  -99.12099539999997  19.445398705606472  
6    POINT (-99.18180 19.48600)            -99.1818              19.486  
7    POINT (-99.20420 19.47490)            -99.2042             19.4749  
..                          ...                 ...                 ...  
205  POINT (-99.06300 19.42160)             -99.063             19.4216  
206  POINT (-99.09699 19.42847)            -99.0967             19.4285  
207  POINT (-99.11960 19.42530)            -99.1196             19.4253  
208  POINT (-99.11220 19.44520)            -99.1122             19.4452  
209  POINT (-99.24820 19.27360)            -99.2482             19.2736  

[195 rows x 6 columns]

In [21]:
df_sk_new=geo_df_list[geo_df_list['tipo_centr'] =='T-III']

In [22]:
df_sk_new.reset_index(inplace=True)

In [23]:
CMpoints=[]
for i in range(len(df_sk_new)): 
    CMpoints.append([df_sk_new.LONGITUD.iloc[i],df_sk_new.LATITUD.iloc[i]])

In [24]:
import random
for i in range(10):
    
    print(int(random.randint(3, 9))*0.1)

0.30000000000000004
0.5
0.7000000000000001
0.5
0.8
0.5
0.9
0.30000000000000004
0.7000000000000001
0.30000000000000004


In [25]:
list_col=['Ocupacion','Servicios','Planta']

In [26]:
df_carac= pd.DataFrame(np.random.rand(len(df_sk_new),3), columns=list_col)

In [27]:
df_carac.head()

Ocupacion  Servicios    Planta
0   0.849615   0.381382  0.567168
1   0.026371   0.210082  0.694931
2   0.796381   0.340490  0.459349
3   0.056331   0.435946  0.667305
4   0.818004   0.763306  0.664089

In [28]:
df_carac.mean()

Ocupacion    0.521646
Servicios    0.525266
Planta       0.501362
dtype: float64

In [29]:
df_carac.shape[1]

3

In [30]:
POND_com=np.random.rand(len(df_carac.columns))

In [31]:
df_carac.iloc[:,1]

0     0.381382
1     0.210082
2     0.340490
3     0.435946
4     0.763306
5     0.490764
6     0.207389
7     0.188542
8     0.385372
9     0.981363
10    0.697920
11    0.612264
12    0.364640
13    0.623251
14    0.710486
15    0.744287
16    0.760714
17    0.519742
18    0.619815
19    0.746204
20    0.973353
21    0.887872
22    0.072576
23    0.408604
24    0.549481
25    0.640572
26    0.543741
27    0.097912
28    0.383684
29    0.274177
30    0.857392
31    0.227292
32    0.852155
33    0.661034
34    0.703603
35    0.994453
36    0.960571
37    0.361814
38    0.807990
39    0.676949
40    0.090494
41    0.526802
42    0.339098
43    0.064673
44    0.680120
45    0.648640
46    0.050152
47    0.266899
48    0.022891
49    0.972009
50    0.321952
51    0.599329
52    0.408904
53    0.906653
54    0.832440
55    0.657283
56    0.062749
57    0.606839
58    0.109435
59    0.629429
Name: Servicios, dtype: float64

In [51]:
def prom_ponder(cols,POND_com):
    '''cols,Pond_com -> df,axis'''
    larg=int(cols.shape[1])
    for i in range(larg):
        cols.iloc[:,i]=cols.iloc[:,i]*POND_com[i]
    
    return cols

In [33]:
df_pon=prom_ponder(df_carac,POND_com)

In [34]:
#Pesos 
df_pon_n=df_pon.mean(axis=1)

In [35]:
import folium
import numpy as np
from scipy.spatial import Voronoi, voronoi_plot_2d

# Generate random points
points = np.random.rand(10, 2)
weights = np.random.rand(10)

# Compute the Voronoi diagram
vor = Voronoi(points)

# Compute the weighted distances and assign each region to the closest generator point
region_assignments = []
for i in range(len(vor.regions)):
    region = vor.regions[i]
    if not -1 in region:
        vertices = vor.vertices[region]
        centroid = np.mean(vertices, axis=0)
        min_distance = float('inf')
        min_index = -1
        for j in range(len(points)):
            weighted_distance = weights[j] * dista_eclidiana(centroid , points[j])
            if weighted_distance < min_distance:
                min_distance = weighted_distance
                min_index = j
        region_assignments.append(min_index)



C:\Users\salai\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3440: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\salai\anaconda3\lib\site-packages\numpy\core\_methods.py:181: RuntimeWarning: invalid value encountered in true_divide
  ret = um.true_divide(


In [36]:
region_assignments

[-1, 1, 4, 9, 4, 4]

In [37]:
vor.regions

[[],
 [1, -1, 0],
 [3, -1, 2],
 [5, -1, 0, 4],
 [7, 4, 0, 1, 6],
 [12, 10, 9, 8, 11],
 [11, 2, 3, 8],
 [9, 6, 1, -1, 3, 8],
 [10, 7, 6, 9],
 [12, 5, 4, 7, 10],
 [12, 5, -1, 2, 11]]

In [38]:
def dist_men(a,b,c):
    '''a,b,c -> array(1x2),array(1x2xn),array(1xn)'''    
    min_index_p=0
    dista_min_p=float('inf')
    min_index=0
    dista_min=float('inf')
    for i in range(len(b)):
        
        dist_p=c[i]*dista_eclidiana(a,b[i])
        dist=dista_eclidiana(a,b[i])
        
        if dist_p < dista_min_p:
            
            dista_min_p = dist_p
            min_index_p = i
        
        if dist< dista_min:
            dista_min = dist
            min_index = i
        
    return min_index,dista_min,min_index_p,dista_min_p
        

In [39]:
points = np.random.rand(10, 2)
weights = np.random.rand(10)

In [40]:
points

array([[0.12290507, 0.88357941],
       [0.21937915, 0.00274949],
       [0.00325091, 0.2530141 ],
       [0.6017077 , 0.10248695],
       [0.09051896, 0.00909292],
       [0.88120659, 0.92723918],
       [0.45445326, 0.42109556],
       [0.41850812, 0.64719251],
       [0.85712901, 0.35724821],
       [0.87017917, 0.95889531]])

In [41]:
np.random.rand(10)

array([0.22471162, 0.37407508, 0.07160473, 0.6164235 , 0.73429682,
       0.02342972, 0.0331913 , 0.64966331, 0.5304049 , 0.14918737])

In [48]:
point = np.random.rand(2)

In [49]:
point

array([0.6746141 , 0.98716948])

In [50]:
dist_men(point,points,weights)

(9, 0.019522562987650538, 5, 0.003028061491260412)

In [52]:
import googlemaps

# Ingresa tu clave de API de Google Maps
gmaps = googlemaps.Client(key='AIzaSyCvlIe2RZHyhs228biG7HGTOcgyaIU_3sc')

# Define las ubicaciones de origen y destino
origen = "San Francisco, CA"
destino = "Los Angeles, CA"

# Obtiene la información de la ruta
ruta = gmaps.directions(origen, destino)

# Imprime la información de la ruta
print(ruta)







ModuleNotFoundError: No module named 'googlemaps'